site_name: Jitsi Meet Enterprise
site_description: Complete enterprise Jitsi Meet deployment with Keycloak authentication
site_author: Jason Hempstead
repo_url: https://github.com/gistmgr/jitsi
repo_name: gistmgr/jitsi
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: dracula
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy

plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true